In [1]:
import pandas as pd;
import numpy as np;
import warnings;
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Loading the data to pandas dataframe

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Information Visualization/countries of the world (1).csv')

In [3]:
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             227 non-null    object
 1   Region                              227 non-null    object
 2   Population                          227 non-null    int64
 3   Area (sq. mi.)                      227 non-null    int64
 4   Pop. Density (per sq. mi.)          227 non-null    object
 5   Coastline (coast/area ratio)        227 non-null    object
 6   Net migration                       224 non-null    object
 7   Infant mortality (per 1000 births)  224 non-null    object
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    object
 10  Phones (per 1000)                   223 non-null    object
 11  Arable (%)                          225 non-null    object
 12  Crops (%)                           225 non-null    object
 13  Other (%)                           225 non-null    object
 14  Climate                             205 non-null    object
 15  Birthrate                           224 non-null    object
 16  Deathrate                           223 non-null    object
 17  Agriculture                         212 non-null    object
 18  Industry                            211 non-null    object
 19  Service                             212 non-null    object
dtypes: float64(1), int64(2), object(17)
memory usage: 35.6+ KB

# Renaming the columns with more readability

In [5]:
# Renaming columns
df.columns = ['Country', 'Region', 'Population', 'Area', 'Pop_Density', 'Coastline_Ratio', 'Net_Migration', 'Infant_Mortality', 'GDP_Per_Capita', 'Literacy_percentage', 'Phones', 'Arable_percentage', 'Crops_percentage', 'Other_percentage', 'Climate', 'Birthrate', 'Deathrate', 'Agriculture', 'Industry', 'Service']

# Display the DataFrame with updated column names
df.head()

,Country,Region,Population,Area,Pop_Density,Coastline_Ratio,Net_Migration,Infant_Mortality,GDP_Per_Capita,Literacy_percentage,Phones,Arable_percentage,Crops_percentage,Other_percentage,Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

# Preprocessing the Dataset

## Replacing the values ',' with '.'

In [6]:
df.replace(',', '.', regex=True, inplace=True)

In [7]:
df.head()

,Country,Region,Population,Area,Pop_Density,Coastline_Ratio,Net_Migration,Infant_Mortality,GDP_Per_Capita,Literacy_percentage,Phones,Arable_percentage,Crops_percentage,Other_percentage,Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700.0,36.0,3.2,12.13,0.22,87.65,1,46.6,20.34,0.38,0.24,0.38
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500.0,86.5,71.2,21.09,4.42,74.49,3,15.11,5.22,0.232,0.188,0.579
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31,6000.0,70.0,78.1,3.22,0.25,96.53,1,17.14,4.61,0.101,0.6,0.298
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000.0,97.0,259.5,10,15,75,2,22.46,3.27,NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.6,4.05,19000.0,100.0,497.2,2.22,0,97.78,3,8.71,6.25,NaN,NaN,NaN

## Checking the null values for every column

In [8]:
df.isnull().sum().sort_values(ascending=False)

Climate                22
Literacy_percentage    18
Industry               16
Service                15
Agriculture            15
Deathrate               4
Phones                  4
Infant_Mortality        3
Net_Migration           3
Birthrate               3
Arable_percentage       2
Crops_percentage        2
Other_percentage        2
GDP_Per_Capita          1
Region                  0
Coastline_Ratio         0
Pop_Density             0
Area                    0
Population              0
Country                 0
dtype: int64

In [9]:
col = df.columns
num_col = df.columns[4:]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country              227 non-null    object
 1   Region               227 non-null    object
 2   Population           227 non-null    int64
 3   Area                 227 non-null    int64
 4   Pop_Density          227 non-null    object
 5   Coastline_Ratio      227 non-null    object
 6   Net_Migration        224 non-null    object
 7   Infant_Mortality     224 non-null    object
 8   GDP_Per_Capita       226 non-null    float64
 9   Literacy_percentage  209 non-null    object
 10  Phones               223 non-null    object
 11  Arable_percentage    225 non-null    object
 12  Crops_percentage     225 non-null    object
 13  Other_percentage     225 non-null    object
 14  Climate              205 non-null    object
 15  Birthrate            224 non-null    object
 16  Deathrate            223 non-null    object
 17  Agriculture          212 non-null    object
 18  Industry             211 non-null    object
 19  Service              212 non-null    object
dtypes: float64(1), int64(2), object(17)
memory usage: 35.6+ KB

## Converting the datatype from object to float

In [11]:
df.iloc[:,4:] = df.iloc[:,4:].astype('float').round(2)

In [12]:
df.head()

,Country,Region,Population,Area,Pop_Density,Coastline_Ratio,Net_Migration,Infant_Mortality,GDP_Per_Capita,Literacy_percentage,Phones,Arable_percentage,Crops_percentage,Other_percentage,Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700.0,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.38,0.24,0.38
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500.0,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.23,0.19,0.58
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000.0,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.10,0.60,0.30
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000.0,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000.0,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,NaN,NaN,NaN

## Filling the Missing values according to the mean of the specific region

In [13]:
# Taking the mean according to 'Region' and replacing with mean value
for i in num_col:
  df[i] = (df[i].fillna(df.groupby('Region')[i].transform('mean')).astype(float)).round(2)

In [14]:
df.head()

,Country,Region,Population,Area,Pop_Density,Coastline_Ratio,Net_Migration,Infant_Mortality,GDP_Per_Capita,Literacy_percentage,Phones,Arable_percentage,Crops_percentage,Other_percentage,Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700.0,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.38,0.24,0.38
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500.0,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.23,0.19,0.58
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000.0,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.10,0.60,0.30
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000.0,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,0.18,0.22,0.61
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000.0,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,0.04,0.25,0.71

# Checking if any null values remaining

In [15]:
df.isnull().sum().sort_values(ascending=False)

Country                0
Region                 0
Industry               0
Agriculture            0
Deathrate              0
Birthrate              0
Climate                0
Other_percentage       0
Crops_percentage       0
Arable_percentage      0
Phones                 0
Literacy_percentage    0
GDP_Per_Capita         0
Infant_Mortality       0
Net_Migration          0
Coastline_Ratio        0
Pop_Density            0
Area                   0
Population             0
Service                0
dtype: int64

In [16]:
df.iloc[:,8] = df.iloc[:,8].astype('int')
df.iloc[:,14] = df.iloc[:,14].astype('int')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country              227 non-null    object
 1   Region               227 non-null    object
 2   Population           227 non-null    int64
 3   Area                 227 non-null    int64
 4   Pop_Density          227 non-null    float64
 5   Coastline_Ratio      227 non-null    float64
 6   Net_Migration        227 non-null    float64
 7   Infant_Mortality     227 non-null    float64
 8   GDP_Per_Capita       227 non-null    int64
 9   Literacy_percentage  227 non-null    float64
 10  Phones               227 non-null    float64
 11  Arable_percentage    227 non-null    float64
 12  Crops_percentage     227 non-null    float64
 13  Other_percentage     227 non-null    float64
 14  Climate              227 non-null    int64
 15  Birthrate            227 non-null    float64
 16  Deathrate            227 non-null    float64
 17  Agriculture          227 non-null    float64
 18  Industry             227 non-null    float64
 19  Service              227 non-null    float64
dtypes: float64(14), int64(4), object(2)
memory usage: 35.6+ KB

In [18]:
df.head()

,Country,Region,Population,Area,Pop_Density,Coastline_Ratio,Net_Migration,Infant_Mortality,GDP_Per_Capita,Literacy_percentage,Phones,Arable_percentage,Crops_percentage,Other_percentage,Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700,36.0,3.2,12.13,0.22,87.65,1,46.60,20.34,0.38,0.24,0.38
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500,86.5,71.2,21.09,4.42,74.49,3,15.11,5.22,0.23,0.19,0.58
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000,70.0,78.1,3.22,0.25,96.53,1,17.14,4.61,0.10,0.60,0.30
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000,97.0,259.5,10.00,15.00,75.00,2,22.46,3.27,0.18,0.22,0.61
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000,100.0,497.2,2.22,0.00,97.78,3,8.71,6.25,0.04,0.25,0.71

# Saving the Dataframe to a .csv file

#

In [19]:
df.to_csv('/content/drive/MyDrive/Information Visualization/Group_4_Countries_of_the_world_cleaned.csv', index=False)